version: '3.7'

services:
  web:
    restart: always
    build: ./app
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - mongodb
  mongodb:
    restart: always
    image: mongo
    volumes:
      - init_db:/var/lib/mongodb/data/docker-entrypoint-initdb.d
      - data_db:/var/lib/mongodb/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongoadmin
      - MONGO_INITDB_DATABASE=djanmon
    command: mongod --port 27017 --auth
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongoadmin
volumes:
  init_db:
  data_db: