version: '3.7'
services:
  web:
    restart: always
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - es
  db:
    restart: always
    image: postgres:12.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=djanes
  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - es
  es:
    image: elasticsearch:7.8.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/var/lib/elasticsearch/data/
    ports:
      - 9200:9200
volumes:
  postgres_data:
  elasticsearch_data: