# Generated by Django 3.0.7 on 2024-11-25 03:36

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, null=True, unique=True)),
                ('making_time', models.CharField(max_length=50, null=True, unique=True)),
                ('serves', models.CharField(max_length=50, null=True, unique=True)),
                ('ingredients', models.CharField(max_length=50, null=True, unique=True)),
                ('cost', models.IntegerField(null=True, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
